import type { MatchRecordDto, RankingEntryDto } from '../api/contracts';

/**
 * ============================================================================
 *  MOCK DATABASE — the "server" state
 * ============================================================================
 *
 * A single in-memory store shared by every handler, which is what makes the two
 * tabs consistent: a match submitted through `POST /matches` is immediately
 * visible to `GET /matches` AND `GET /ranking`, because they read the same
 * records.
 *
 * PERSISTENCE IS A REQUIREMENT, NOT A CONVENIENCE: the brief asks for confirmed
 * records to survive a refresh. State is written to localStorage on mutation
 * (debounced), and restored on boot.
 *
 * `revision` is monotonic per collection. It is the mechanism that lets the
 * client detect and discard an out-of-order response.
 */

const STORAGE_KEY = 'pb.msw.db.v1';
const SCHEMA_VERSION = 1;

/**
 * Bump when fixture generation changes (balance values, fixture scores, the
 * fingerprint algorithm). Stored rows generated by an older tag are discarded on
 * restore instead of lingering as invisible records.
 */
const SEED_TAG = 2;

/** Debounce so a burst of submissions writes once. */
const PERSIST_DEBOUNCE_MS = 250;

export interface MockDbShape {
  readonly schemaVersion: number;
  /** Identifies which generator produced the fixture rows in this snapshot. */
  readonly seedTag: number;
  /** Monotonic counters; never decrease, even after a reset. */
  readonly rankingRevision: number;
  readonly matchesRevision: number;
  readonly matches: readonly MatchRecordDto[];
}

const emptyDb = (): MockDbShape => ({
  schemaVersion: SCHEMA_VERSION,
  seedTag: SEED_TAG,
  rankingRevision: 1,
  matchesRevision: 1,
  matches: [],
});

export class MockDatabase {
  private state: MockDbShape = emptyDb();
  private persistTimer: ReturnType<typeof setTimeout> | null = null;

  constructor(private readonly storage: Storage | null = safeLocalStorage()) {
    this.restore();
  }

  /* ------------------------------------------------------------------ state */

  get rankingRevision(): number {
    return this.state.rankingRevision;
  }

  get matchesRevision(): number {
    return this.state.matchesRevision;
  }

  get matches(): readonly MatchRecordDto[] {
    return this.state.matches;
  }

  bumpRankingRevision(): number {
    this.state = { ...this.state, rankingRevision: this.state.rankingRevision + 1 };
    this.schedulePersist();
    return this.state.rankingRevision;
  }

  bumpMatchesRevision(): number {
    this.state = { ...this.state, matchesRevision: this.state.matchesRevision + 1 };
    this.schedulePersist();
    return this.state.matchesRevision;
  }

  findMatch(matchId: string): MatchRecordDto | undefined {
    return this.state.matches.find((record) => record.matchId === matchId);
  }

  /**
   * Idempotent insert.
   *
   * @returns the stored record and whether it was newly created. A repeat call
   *          with the same `matchId` is NOT an error: it returns the existing
   *          record, which is what makes a retried submission safe.
   */
  upsertMatch(record: MatchRecordDto): { record: MatchRecordDto; created: boolean } {
    const existing = this.findMatch(record.matchId);
    if (existing !== undefined) {
      return { record: existing, created: false };
    }

    this.state = { ...this.state, matches: [...this.state.matches, record] };
    this.bumpMatchesRevision();
    // A new match changes the ranking too, and both tabs must refresh.
    this.bumpRankingRevision();
    return { record, created: true };
  }

  reset(seed?: readonly MatchRecordDto[]): void {
    this.state = seed === undefined ? emptyDb() : { ...emptyDb(), matches: [...seed] };
    this.flushPersist();
  }

  /* ------------------------------------------------------------ persistence */

  private schedulePersist(): void {
    if (this.storage === null) return;
    if (this.persistTimer !== null) clearTimeout(this.persistTimer);

    this.persistTimer = setTimeout(() => {
      this.persistTimer = null;
      this.flushPersist();
    }, PERSIST_DEBOUNCE_MS);
  }

  /** Writes immediately. Called on reset so a "reset mocks" button is reliable. */
  flushPersist(): void {
    if (this.persistTimer !== null) {
      clearTimeout(this.persistTimer);
      this.persistTimer = null;
    }
    if (this.storage === null) return;
    try {
      this.storage.setItem(STORAGE_KEY, JSON.stringify(this.state));
    } catch {
      // Quota or private mode: the mock server simply becomes memory-only.
    }
  }

  /**
   * Restores persisted state, DISCARDING anything seeded under a stale schema of
   * the fixture generator.
   *
   * The `seedTag` exists because fixtures embed the configuration fingerprint.
   * When the balancing values change, the fingerprint changes too — and records
   * persisted under the old one become invisible to the ranking filter, leaving a
   * permanently empty table with no way for the player to tell why. Bumping the
   * tag on any change that affects generated data invalidates those rows
   * automatically, while genuine player submissions are preserved separately by
   * `ensureSeeded`.
   */
  private restore(): void {
    if (this.storage === null) return;
    try {
      const raw = this.storage.getItem(STORAGE_KEY);
      if (raw === null) return;

      const parsed: unknown = JSON.parse(raw);
      if (!isDbShape(parsed)) return;

      const stale =
        parsed.seedTag !== SEED_TAG ||
        parsed.matches.some((record) => record.matchId.startsWith('fixture-'));

      if (stale) {
        // Keep real submissions, drop generated ones.
        this.state = {
          ...parsed,
          matches: parsed.matches.filter((record) => !record.matchId.startsWith('fixture-')),
        };
        return;
      }

      this.state = parsed;
    } catch {
      // Corrupt storage must never break the app; start clean.
      this.state = emptyDb();
    }
  }
}

const isDbShape = (value: unknown): value is MockDbShape => {
  if (typeof value !== 'object' || value === null) return false;
  const record = value as Record<string, unknown>;
  return (
    record['schemaVersion'] === SCHEMA_VERSION &&
    typeof record['seedTag'] === 'number' &&
    typeof record['rankingRevision'] === 'number' &&
    typeof record['matchesRevision'] === 'number' &&
    Array.isArray(record['matches'])
  );
};

const safeLocalStorage = (): Storage | null => {
  try {
    return typeof localStorage === 'undefined' ? null : localStorage;
  } catch {
    return null;
  }
};

/* -------------------------------------------------------------------------- */
/* Ranking projection                                                          */
/* -------------------------------------------------------------------------- */

/**
 * DETERMINISTIC ORDER — the brief requires an explicit, reproducible tie-break.
 *
 *   1. score DESC            — the primary objective
 *   2. duration ASC          — same score in less time is the better run
 *   3. finishedAt ASC        — earlier run wins the tie
 *   4. matchId ASC           — final, total tie-break; no two rows can compare equal
 *
 * The `matchId` clause is what makes the sort a TOTAL ORDER, so two players with
 * identical numbers never swap places between requests.
 */
export const compareRankingEntries = (
  a: Pick<RankingEntryDto, 'score' | 'effectiveDurationMs' | 'finishedAtIso' | 'matchId'>,
  b: Pick<RankingEntryDto, 'score' | 'effectiveDurationMs' | 'finishedAtIso' | 'matchId'>,
): number => {
  if (a.score !== b.score) return b.score - a.score;
  if (a.effectiveDurationMs !== b.effectiveDurationMs) {
    return a.effectiveDurationMs - b.effectiveDurationMs;
  }
  if (a.finishedAtIso !== b.finishedAtIso) {
    return a.finishedAtIso < b.finishedAtIso ? -1 : 1;
  }
  return a.matchId < b.matchId ? -1 : 1;
};

/** Projects match records into ranking entries, ranked and filtered. */
export const buildRanking = (
  matches: readonly MatchRecordDto[],
  configFingerprintFilter: string,
): readonly RankingEntryDto[] =>
  matches
    .filter((record) => record.configFingerprint === configFingerprintFilter)
    .map((record) => ({
      rank: 0, // assigned after sorting
      matchId: record.matchId,
      playerId: record.playerId,
      playerName: record.playerName,
      score: record.score,
      effectiveDurationMs: record.effectiveDurationMs,
      endReason: record.endReason,
      configFingerprint: record.configFingerprint,
      finishedAtIso: record.finishedAtIso,
    }))
    .sort(compareRankingEntries)
    .map((entry, index) => ({ ...entry, rank: index + 1 }));

/* -------------------------------------------------------------------------- */
/* Module singleton                                                             */
/* -------------------------------------------------------------------------- */

/**
 * One database for the whole app.
 *
 * Handlers must close over a single instance, otherwise `POST` and `GET` would
 * read different stores and the two tabs would disagree — precisely the
 * inconsistency the brief forbids.
 */
export const mockDb = new MockDatabase();
